### ISSUE TITLE
Need conversion support for java.time.LocalDate, java.time.LocalDateTime and java.time.Instant

### ISSUE THREAD

**Issue by abhilater** [helpshift/mongrove#4]
With Mongo Java driver 3.7, we have support for java.time types as described here 
http://mongodb.github.io/mongo-java-driver/3.7/whats-new/

```
JSR-310 Instant, LocalDate & LocalDateTime support
Support for Instant, LocalDate and LocalDateTime has been added to the driver.
```
We can add the relevant conversions to the ConvertToBsonDocument protocol definitions

I can open a pull request for this change if you think we need this.

**Comment by sumeetkoli** [comment]
Thank you @abhilater for raising this issue and the PR.
Your [PR](https://github.com/helpshift/mongrove/pull/5) is now merged and conversion support for these date types in now present in mongrove version `0.3.0`.
